#!/bin/bash
echo "Hand made make script for Staff Scheduler Library .." 
echo "Written by Ammar Qammaz a.k.a AmmarkoV :) "
 

echo "Compiling files.."
 
gcc -c SCCoreMemory.c -o SCCoreMemory.o
gcc -c SCDays.c -o SCDays.o
gcc -c SCJob.c -o SCJob.o
gcc -c SCPerson.c -o SCPerson.o 
gcc -c ScheduleCreatorCalender.c -o ScheduleCreatorCalender.o
gcc -c ScheduleCreatorCore.c -o ScheduleCreatorCore.o
gcc -c ScheduleCreatorFileIO.c -o ScheduleCreatorFileIO.o 
gcc -c SchedulePrintouts.c -o SchedulePrintouts.o 
gcc -c ScheduleSolver.c -o ScheduleSolver.o 
gcc -c ScheduleSorting.c -o ScheduleSorting.o 
gcc -c ScheduleStatistics.c -o ScheduleStatistics.o 
gcc -c main.c -o main.o 

FILES="main.o SCCoreMemory.o SCDays.o SCJob.o SCPerson.o ScheduleCreatorCore.o ScheduleCreatorFileIO.o SchedulePrintouts.o ScheduleCreatorCalender.o ScheduleStatistics.o ScheduleSorting.o ScheduleSolver.o "


echo "Linking files.."
ar rcs libScheduleCreator.a $FILES

echo "Cleaning compiled object files.."
rm $FILES 


echo "Done.."
exit 0
